version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zdn_booking_server
    env_file:
      - .env
    ports:
      - '5000:5000'
    volumes:
      - ./src:/app/src